### ISSUE TITLE
Checkli

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-ux-research#2]
Yesterday when I was researching reviews/summaries for the Checklist Manifesto for https://github.com/dwyl/product-roadmap/pull/11 I _stumbled_ upon https://blog.checkli.com/checklist-manifesto
![image](https://user-images.githubusercontent.com/194400/57014422-f4d9dc00-6c07-11e9-8334-16ea344308c8.png)
(_I did not share it as a link in the PR I'm preparing for our "Product Roadmap" because I don't want anyone at "Checkli" to remotely think that we "copied" their idea ...

This blog post (_by the company's solo non-technical founder_) tells me _several_ things:
1. **in-bound marketing _works_** and writing blog posts is a _high_ priority for us.
2. ***Marvin Russell*** https://www.linkedin.com/in/marvinrussell the founder of checkli.com 
![image](https://user-images.githubusercontent.com/194400/57014517-58640980-6c08-11e9-9d20-aa08b3f52d2d.png)
Does not _personally_ have the technical skills to compete with us and he has hired a technical person to build the site. (see below).
3. There are other people out there who are not only _aware_ of Atul's book (Checklist Manifest), they are _acting_ on building something towards it. 

# Key People

https://www.checkli.com/company
![image](https://user-images.githubusercontent.com/194400/57015660-e8588200-6c0d-11e9-85f5-7067b79a15e6.png)
The only technical person in the company is ***Simon Kateregga***: https://github.com/simonkatz
![image](https://user-images.githubusercontent.com/194400/57015689-0faf4f00-6c0e-11e9-92b9-6a4cfc9cd12b.png)

# Technical Overview

Simons' pinned GH repos informs us (_with near certainty_) that the Checkli backend is build in **Laravel `PHP`** (_which is not a "bad" thing, I want **all** my "competitors" to use `PHP`!_)
Whereas the frontend is built with Angular
https://builtwith.com/?https%3a%2f%2fwww.checkli.com
![image](https://user-images.githubusercontent.com/194400/57015750-58670800-6c0e-11e9-8674-0dea2d468aa6.png)
Simon has made _zero_ contributions to other open source projects. `#Taker`
![image](https://user-images.githubusercontent.com/194400/57015793-8f3d1e00-6c0e-11e9-8d5b-7ec2d9c7229c.png)
But he has built a website for a school in Uganda: https://github.com/simonkatz/www.betterviewschool.com https://www.betterviewschool.com
![image](https://user-images.githubusercontent.com/194400/57016326-708c5680-6c11-11e9-85f9-d3924b1e7944.png)
Which is commendable ... 
even though it's a single-pages brochureware site that nobody at the school can update
![image](https://user-images.githubusercontent.com/194400/57016761-d7127400-6c13-11e9-80be-8ceb26ac07f0.png)

it's "_better than nothing_" and gets the message out to prospective parents.

![image](https://user-images.githubusercontent.com/194400/57016825-1c36a600-6c14-11e9-9036-b96facced1c8.png)

Personal website: https://www.simonkateregga.com looks good. 
![image](https://user-images.githubusercontent.com/194400/57016358-9a457d80-6c11-11e9-8a8f-00e674d94554.png)

# Home Page Analysis

Headline stats: "Over 1 Million checklists made and 10 million tasks create d, so far."
![image](https://user-images.githubusercontent.com/194400/57015921-315d0600-6c0f-11e9-90a4-4f5e861aa834.png)

I _highly_ doubt this stat, are they including the checklists they created during UAT/QA...?

Most popular checklists: https://www.checkli.com/checklists/popular

## Templates?

https://www.checkli.com/explore
![image](https://user-images.githubusercontent.com/194400/57017039-3329c800-6c15-11e9-8bb1-ba74642b4b32.png)

New/latest checklists:
![image](https://user-images.githubusercontent.com/194400/57017071-548ab400-6c15-11e9-93f5-2dd6bbb1ccaa.png)

Top Publishers list in the right-hand column:
![image](https://user-images.githubusercontent.com/194400/57015879-007cd100-6c0f-11e9-91ea-7b401d34b33b.png)

The _first_ person in the "Top Publishers" list is: https://www.checkli.com/kristenstack 
![image](https://user-images.githubusercontent.com/194400/57016012-b2b49880-6c0f-11e9-8e73-b0aab4765b55.png)
Kirsten Stack https://www.kristenstack.com https://www.linkedin.com/in/kristennicolestack
is clearly an SEO freelancer who is mates with Marvin (_non-technical founder_) and 
![image](https://user-images.githubusercontent.com/194400/57016029-d1b32a80-6c0f-11e9-8082-f06d0aee54b3.png)

Her "most popular" (on Checkli) "On Page SEO Checklist":
https://www.checkli.com/checklists/kristenstack/on-page-seo-checklist
![image](https://user-images.githubusercontent.com/194400/57016214-da583080-6c10-11e9-8a08-515ceeca544b.png)
Which is clearly a link-back to: https://www.kristenstack.com/blog/top-10-on-page-seo-tips
![image](https://user-images.githubusercontent.com/194400/57016251-02e02a80-6c11-11e9-9dfa-2f779faa9d85.png)

White text on a yellow background ... 🙄 (_color/contrast theory not a strong point_)

## Footer

![image](https://user-images.githubusercontent.com/194400/57017547-8bfa6000-6c17-11e9-83a2-d0cae55cc96c.png)

# UX Walkthrough

## Become a Publisher:
Copy:
> Grow your brand by driving traffic, leads, and sales to your website. Checklists take minutes to publish and can rank as well as blog posts.
![image](https://user-images.githubusercontent.com/194400/57017102-784dfa00-6c15-11e9-9c8c-8365020efffd.png)
Clearly Marvin & co. know _very_ well that the secret to organic growth (& SEO) is building a network of publishers who create a checklist and cross-post it to their content site. (_this is 

## New Anonymous Checklist

https://www.checkli.com/checklists/view/5cc9930941ecc
![image](https://user-images.githubusercontent.com/194400/57017667-04f9b780-6c18-11e9-8e95-51847d5889fe.png)

Clicking the "Save" CTA results in the following registration modal:
![image](https://user-images.githubusercontent.com/194400/57017682-1216a680-6c18-11e9-9b07-3859e8fc1baa.png)

But the "guest view" link is valid in incognito (_different web browser_):
https://www.checkli.com/checklists/guest_view/5cc9930941ecc
![image](https://user-images.githubusercontent.com/194400/57017735-55711500-6c18-11e9-8e20-579bd17c6a97.png)
Which means that content persists and is public even for anon users.
This is a _good_ thing for reducing friction to adoption as noted in: https://github.com/dwyl/time/issues/58

In the incognito window, I can check-off items on the list without requiring signin:
![image](https://user-images.githubusercontent.com/194400/57017814-b567bb80-6c18-11e9-8ec2-bd84e16515fc.png)

In a _separate_ (_also incognito_) window (_this time in Safari_),
When I attempt to set a checklist item to "done" I am promoted with the following modal:
![image](https://user-images.githubusercontent.com/194400/57018030-9ddd0280-6c19-11e9-934e-742bc3d0c112.png)

Back in my _original_ (Chrome) window I now see that three tasks are completed:
![image](https://user-images.githubusercontent.com/194400/57018062-c533cf80-6c19-11e9-82b6-f01f61b06b89.png)
And next to the checkbox I see the first two letters of the name of the person I entered.

With JS disabled I see no content:
![image](https://user-images.githubusercontent.com/194400/57017930-31fa9a00-6c19-11e9-8ed7-13fb66118df6.png)
The layout/template is server-side rendered by Laravel and then the actual checklist is client-side rendered with Angular.

# Errors

The _home_ page has https://www.checkli.com has a `401`(Unauthorized)
 Auth error attempting to retrieve data from the API: https://www.checkli.com/api/v1/me 401
![image](https://user-images.githubusercontent.com/194400/57016071-16d75c80-6c10-11e9-8a8b-f6aeca344663.png)

Attempting to visit https://www.checkli.com/rss resulted in the following XML error:
![image](https://user-images.githubusercontent.com/194400/57016051-f3141680-6c0f-11e9-9757-2d848a1355ab.png)

# Crunchbase

https://www.crunchbase.com/organization/checkli
![image](https://user-images.githubusercontent.com/194400/57016941-b4cd2600-6c14-11e9-9105-9831b1214bcd.png)

# Conclusion

+ [x] Checkli has a good domain for solving the problem of checklists.
+ [x] They have a blog https://blog.checkli.com with fairly regular+relevant content (_which is unsurprising given that the 
+ [x] They are doing _several_ things _right_:
  + [x] Guest/Anonymous content creation (_without signup_) 

On the basis that the site does not have much traction (_visible from the low "view count" for the "most popular" checklists_), I am not going to spend any more time on this initial research.
We can re-visit this and do more extensive research in a few months time.
Right now we have _much_ better things to do; defining the MVP features!

# Todo

+ [ ] Re-visit and check for more traction in 6 months.
