### ISSUE TITLE
mymorningroutine.com

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-ux-research#3]
https://mymorningroutine.com/routines mentioned in https://github.com/nelsonic/nelsonic.github.io/issues/145#issuecomment-488254705
![image](https://user-images.githubusercontent.com/194400/57018114-00ce9980-6c1a-11e9-8c7a-78988cf8d655.png)

# Todo

+ [x] Go through the website to find out:
  + [x] Are the morning routines a simple list or an interactive checklist?
sample routine: https://mymorningroutine.com/shirley-meerson
![image](https://user-images.githubusercontent.com/194400/57018194-63c03080-6c1a-11e9-8c8d-2169aec8f340.png)
  > it's more of an interview / listicle hybrid with nothing to _interact_ with.
  + [x] What are the approximate number of "users" for the site?
   the "Join over 12,000 subscribers and get a brand new morning routine every Wednesday!" suggests there are 12k people signed up to the newsletter. If we estimate 10% "engagement", we could assume 1.2k "users". 

https://mymorningroutine.com/about "magazine" ...
![image](https://user-images.githubusercontent.com/194400/57018276-be598c80-6c1a-11e9-9c1e-2834bf3762d5.png)

![image](https://user-images.githubusercontent.com/194400/57018720-6de32e80-6c1c-11e9-898a-6a5b57120405.png)

They are not building an app to _execute_ on the vast array of morning routines.
(_at least not on the surface ..._) They appear to be a purely content-driven site.
If we were able to give them an "Affiliate" link to drive people to our App it could be "win-win".

![image](https://user-images.githubusercontent.com/194400/57018303-daf5c480-6c1a-11e9-94f4-dfccb6e5208d.png)

https://mymorningroutine.com/press/
![image](https://user-images.githubusercontent.com/194400/57018306-e0eba580-6c1a-11e9-989c-eb251bd7388d.png)

https://mymorningroutine.com/deals
![image](https://user-images.githubusercontent.com/194400/57018325-f5c83900-6c1a-11e9-8a38-97c60aa00750.png)

![image](https://user-images.githubusercontent.com/194400/57018228-86524980-6c1a-11e9-9490-1be5dd2923f1.png)

![image](https://user-images.githubusercontent.com/194400/57018235-8e11ee00-6c1a-11e9-9da0-1083edb862e0.png)

![image](https://user-images.githubusercontent.com/194400/57018238-9538fc00-6c1a-11e9-9bec-23b74e9c311b.png)

https://mymorningroutine.com/participate/
![image](https://user-images.githubusercontent.com/194400/57018259-a71a9f00-6c1a-11e9-998d-657f6922b990.png)

A google form:
![image](https://user-images.githubusercontent.com/194400/57018339-0d072680-6c1b-11e9-8afa-25453723c563.png)

# Conclusion

This is a _curated_ content site designed to drive traffic to a page of Amazon Affiliate links and sell their book: https://www.amazon.com/My-Morning-Routine-Successful-Inspired/dp/0735220271
![image](https://user-images.githubusercontent.com/194400/57018425-68d1af80-6c1b-11e9-818c-960b55ec506a.png)
47 reviews mostly positive, but the Top review is quite scathing ...
![image](https://user-images.githubusercontent.com/194400/57018460-90c11300-6c1b-11e9-9d1f-814fe6898871.png)
It's a similar story on the UK site:
![image](https://user-images.githubusercontent.com/194400/57018528-d382eb00-6c1b-11e9-98d0-35063dec9b38.png)

This volume of reviews indicates the book has sold _poorly_. 📉 

It _could_ be worth attempting to partner with them and/or sponsor a newsletter (_depending on cost_) once we have our MVP tested and ready for "warm lead" users.
https://mymorningroutine.com/sponsor/
![image](https://user-images.githubusercontent.com/194400/57018598-0fb64b80-6c1c-11e9-82c3-d96f71414e5c.png)

# _Next_ Action: Re-visit once we have "Affiliate Links" in our MVP
