### ISSUE TITLE
Modals 🙅 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-ux-research#38]
A **`modal`** was used in one of our tutorials https://github.com/dwyl/learn-alpine.js/pull/5/files#r1012307859 

![image](https://user-images.githubusercontent.com/194400/199604980-3a7d8c6a-82e3-488b-aebf-e3c6c28d9e1d.png)

I want to capture ***why*** we don't want to use them. ***ever***.

# Todo

+ [ ] Describe the _history_ of modals. See: https://accessuse.eu/en/modal-dialogs.html
+ [ ] Modals are _not_ the same as built-in/native alerts/prompts! 
+ [ ] Compare Modals to ***Cigarettes***, _fashionable_, you see them often but **_totally_ unnecessary**. 
+ [ ] Explain the _one_ situation where they are acceptable, but _still_ don't!! 
  + [ ] Ref: https://github.com/alphagov/govuk-design-system-backlog/issues/30#issuecomment-537013244
+ [ ] Propose alternative mobile-first/friendly UI/UX that is accessible, performant and requires zero QA time!

**Comment by trickydisco78** [comment]
How about the native dialog element that is built into modern browsers now? This includes lot of usability and accessibility features built in: focus trapping, autofocus on element, inert on document, open and close method, automatic close on esc key.

Example https://web.dev/building-a-dialog-component/

Scott o hara mentions using native dialog now 

>I would recommend either using the native <dialog> element, or you should check out [a11y-dialog](https://github.com/KittyGiraudel/a11y-dialog) for a script that is being actively maintained and delivers a good modal dialog experience.
https://github.com/scottaohara/accessible_modal_window

**Comment by nelsonic** [comment]
Hey @trickydisco78 👋  [how on earth did you find this issue?! 😜 ...]

Yeah, Native dialogs have been available for a while:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#browser_compatibility

As noted in the second checkbox above, Modals are not the same as the _Native_ `dialog`. 
One has been _extensively_ Quality Assurance Tested by the Browser makers, the others not so much.

I would _still_ caution against using them liberally because unless they _add_ to the UX. 🤷‍♂️ 
_Most_ of the time designers/devs use for a Modal when it's _totally_ inappropriate like basic forms!
Much like the way smokers unconsciously reach for a cigarette without even thinking: "_do I **need** to be **killing myself**_?"

Yes, "focus trapping" is a _potentially_ valid scenario ...
But why use a **`modal`** to _overlay_ something when you can just _transition_ to a **_full_-page focus**? 
We have become so _used_ to modals that nobody bothers to ask these questions anymore.
It's like **TV violence**. We think it's "normal" ... and yet, it's really not! 
Violence is exceedingly rare in real life! Modals should be too!

@scottaohara is a good designer and his `modal` is a good example of the ***How*** but fails on the "***Why?***" 
i.e. ***Why*** do designers use Modals?
I contend that modals are the _lazy_ person's UI; they are almost _always_ inappropriately used.
**_Great_ UX** is so seamless that you **_never_ need** to use a **Modal**.
Imagine on-boarding for your favourite video game e.g: Super Mario or Tetris.
There are no Modals! And yet you learn the controls  & game mechanics seamlessly. 
That's _great_ UX design! Only _one_ thing to focus on at any given time. 

Highly recommend watching Bret Victor's  "Inventing on Principle"
https://www.youtube.com/results?search_query=Bret+Victor+Inventing+on+Principle
Specifically the "Why?" section.

## "_You can choose to sleepwalk through life <br /> and accept the path that's been laid out for you. <br />You can choose to accept the world as it is. <br />But you don't have to. <br />If there's something in the world you feel is wrong, <br />and you have a vision for what a better world could be, <br />you can find your guiding principle, and fight for a cause._"

**Comment by trickydisco78** [comment]
Hey.. I found it linked from discussions here: https://github.com/alphagov/govuk-design-system-backlog/issues/30

As part of a project i've been asked to implement a modal. In this instance because of good support i've used the native dialog DOM element.

 I agree with you in a lot of respects. Modals are over used. But in others maybe not. Its a UI pattern that has been used for a long time: think of all the dialog modals that appear on mac and windows OS. They are everywhere! The same with Games: https://www.gameuidatabase.com/index.php?set=1&scrn=902&tag=8&r=1 same with apple

![image](https://user-images.githubusercontent.com/3627429/199949521-601219bc-addd-49ba-9b1c-38bfb22e1a6d.png)

Spotify 
![image](https://user-images.githubusercontent.com/3627429/199949648-1e4df69d-fd9a-4be6-bc38-886c3942e5c9.png)

games
![image](https://user-images.githubusercontent.com/3627429/199950345-9fda145f-24ef-4669-ba2f-c0119de85454.png)

Ios
![image](https://user-images.githubusercontent.com/3627429/199950689-ff3e9238-015d-45e9-84b4-537b4045c8a6.png)
Gmail
![image](https://user-images.githubusercontent.com/3627429/199951180-0ad2847c-9f82-475e-8107-598adb19378f.png)

Or maybe i'm getting confused about the difference between a dialog and a modal? A modal to me is when the background dims behind. I think you should have the ability to light dimiss (cick outside the modal) to close it.

**Comment by nelsonic** [comment]
These are all examples of **Native UI** components which are _extensively_ tested both for pixel-perfection and a11y. ✅ 
I don't think _any_ of these examples are particularly _good_ UX though ... do you? 🤷‍♂️ 

The **`iOS`** dialogues are so ingrained in us that we just think they are "normal" ... 
Apple could just as easily done a better UX and perhaps in a future **`iOS`** we will see one
similar to the "Dynamic Island" ... 🏝️ 😉 

Spotify's use of modals to interrupt the UX flow is particularly egregious! 😠 
I just want to listen to music not have to first read your Advert for Taylor Swift's new _noise_ and dismiss it ... ⏳ 
(BTW: I actually think TayTay's music is dope, just saying not everyone needs to see this "New Release" ...)
I _regularly_ find myself using the Spotify App and _wishing_ there was something better. 💭 

The gmail one is just _horrible_. It' adds no value whatsoever. it's just a UI/UX anti-pattern. 🤦‍♂️ 
They could easily have made that full-screen without any loss of experience. 
In fact I would argue the UX would be _considerably_ better if it was _uncluttered_ by the background noise.  
Forcing people to "Choose a View" before they have interacted with the product is just unnecessary
what a _lame_ onboarding experience. Clearly they have such great market share that they don't have to worry about imposing decision fatigue on people this early in the UX. 🤷‍♂️ 

Sadly,, I don't think this thread is the place I'm going to "_convince_" anyone especially given the ubiquity of modals ...
But I feel the same way about Modals as I do about cigarettes:

![image](https://user-images.githubusercontent.com/194400/199976143-4a2e9d27-821b-4f9a-b0a6-36466ad15dc3.png)

**Comment by scottaohara** [comment]
not really sure why i was @'d in here?  but since i was, i'll just quickly respond to
>is a good designer and his modal is a good example of the How but fails on the "Why?"

odd word choice to say i "failed" on something I never attempted to discuss.  

tbh, i actually agree with 
>I contend that modals are the lazy person's UI; they are almost always inappropriately used.

but, i don't have the time or energy to fight that battle.  Rather, it seems more important to me to help people know how to make them accessible for when they do use them.

good luck to you though.  hope you don't fail ;)

**Comment by nelsonic** [comment]
@scottaohara apologies for spamming you. 🤦‍♂️  Love your work! Thank you all you do for Accessibility. ❤️ 
Apologies for using the word "fail". Didn't mean any disrespect. 🙇 

Just wanted to highlight that your project that has great docs 😍  
doesn't ask/answer the question "_**Why** Use **Modals**_?" ... 🤷‍♀️ 
Not saying it _should_ ... you're fighting the "good" **a11y** fight. 🙈 
just wish more people thought about the "***Why***?" in UI/UX design ... 💭 
so many people building software products haven't read ["Don't Make Me Think"](https://www.amazon.com/Dont-Make-Think-Revisited-Usability/dp/0321965515) or ["The Design of Everyday Things"](https://www.amazon.com/Design-Everyday-Things-Revised-Expanded/dp/0465050654)
As a result the world of Apps/Software is _full_ of "**`Norman` Doors**" with **_horrible_ UX** ... 😢 
https://99percentinvisible.org/article/norman-doors-dont-know-whether-push-pull-blame-design/

Anyway, hope you're both having a great Friday! ☀️

**Comment by trickydisco78** [comment]
How about this opinion

![image](https://user-images.githubusercontent.com/3627429/200805823-8aab324e-cff8-4bbb-8652-7e370abbfb4c.png)

https://twitter.com/anotheruiguy/status/1589743863325167616


Is there concensus on the difference between a modal and a dialog? Even the native dialog element has a showModal() event

**Comment by scottaohara** [comment]
it's not really a matter of consensus.  people either understand these terms, or they use "modal" incorrectly.

**Comment by nelsonic** [comment]
This is the crap I think of whenever I think of Modals:
![image](https://user-images.githubusercontent.com/194400/208245674-cabc63f7-3975-4590-bc0d-b80e8823e200.png)

An unwelcome interruption to the task I'm attempting to perform. [Researching: https://github.com/dwyl/learn-cad-cam-cnc/issues/93 ...]
The person who put this Ad `modal` on this page is _stealing_ time from me.
Reluctantly enabling Add block on chrome. 

![image](https://user-images.githubusercontent.com/194400/208245843-8b031769-aa94-4a25-b57b-027838c32c17.png)

**Comment by nelsonic** [comment]
There appears to be some confusion about what a **`Modal`** is ... This is a modal: 🤮 
https://getbootstrap.com/docs/4.0/components/modal/

![bootstrap-modal-gif](https://user-images.githubusercontent.com/194400/209325793-04810f82-e44e-4c3c-bb8e-1af3c323727e.gif)

The **`Modal`** overlays the screen ***hijacking*** the focus of the viewer and ***forces*** them to **_manually_ dismiss** it. 
This is _horrible_ UX. 

By contrast, the ["***Card***"](https://uxplanet.org/ultimate-guide-for-designing-ui-cards-59488a91b44f) on git-fork "buy" page: https://git-fork.com/buy is **_not_ a `Modal`**:

![image](https://user-images.githubusercontent.com/194400/209348971-9f8614d2-e7f0-450e-9ee4-91bbf300e243.png)

It does hijack the focus of the person viewing the page. It's simply presented as the _suggested_ focal point.

Sadly, when you click on the **`Buy`** button, that's when the **_pointless_ `Modal`** hijacks the screen:

![image](https://user-images.githubusercontent.com/194400/209349694-8ada7675-c7a8-4b88-a8a5-bae7bfa82c60.png)

Why?! 🤷‍♂️ 
Has the person that built this never _used_ **`Amazon`** checkout? 🤷‍♂️ 
**`Amazon`** - the most successful e-commerce platform in the world - _never_ uses **`Modals`**. 
_Surely_ if their objective is _conversion/completion_, just follow the **`Amazon`** checkout process? 
***WHY*** do they feel the need to use a **`Modal`**?! 🤦‍♂️

**Comment by LuchoTurtle** [comment]
I kind of disagree with your opinion on Fork's use of this modal. 
You are suggesting the modal is pointless as it's changing/hijacking the page focus. I believe it's working exactly as intended, especially with the fact that the page is suggesting that you can only buy the license from it. 

But what would the alternative be? Opening a new tab with the [Paddle](https://www.paddle.com/) payment session? In terms of "time wasted (🙄)", I'd waste more time in changing windows and waiting for them to load.

Should the session be changed within the same tab? It would be worse. If I wanted to go back, I would have to wait for the page to load again from the payment session checkout page.

With this modal, I can just close it if I changed my mind about buying the product.

Amazon being the most successful e-commerce in the world has *nothing* to do with how great or bad the shopping experience is (especially checking out when purchasing items).

Here's an annoying example:

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/17494745/209484663-dccc90e4-5532-4c46-905a-0e4053aaa112.png">

Here's me wanting to purchase a [Benjamin Tod](https://www.youtube.com/watch?v=V6SR4lNqjME&ab_channel=WesternAF) vinyl. When I check out, I am navigated to an entirely different page just to fill in card details, etc...

I find myself having to go back to add forgotten items or check other items **countless times** and I'm sure I've wasted more time loading Amazon's big website bundle when I could just have closed a modal and kept looking.

Happy to hear opinions 👍

**Comment by nelsonic** [comment]
Everyone is very welcome to _disagree_ with what I write. Ideally with _evidence_. 🙏 
However this is not a matter of ***opinions***, it's **`data`**. 
**`Amazon`**, _unquestionably_ the **biggest e-commerce company** in the world by **_any_ metric**:
https://www.statista.com/statistics/245340/leading-large-cap-e-commerce-companies-market-cap
![image](https://user-images.githubusercontent.com/194400/209489549-10380794-ad77-4196-93ec-6ffe68416804.png)



Does _not_ use `Modals` in their checkout process. 
This is not for "nostalgia" or lack of engineering resources/talent reasons, 
it's not an _accident_, it's **`100%` all business** for The Jeff!

![image](https://user-images.githubusercontent.com/194400/209486739-5e0166bf-f67b-4ed7-8879-a495f9380cb9.png)

When it comes to **`UX`**, **`Amazon`** has the **`data`**; the **_biggest_ `data` by _far_** ...

![amazon-huge-data](https://user-images.githubusercontent.com/194400/209487420-bbb036f9-bec7-49ac-845a-f1e527fe41e3.jpg)

They have run _many_ **`A/B`** and multivariate tests on their checkout process over the years 
and don't use `Modals` where _matters_ most. This isn't a matter of ***opinion***. 
This is what works for conversion. 
Anyone who wants to make money online and not _waste_ people's time
doesn't need to look any further we _have_ the answer!!

Buuuuuuttttt ... if we are still _curious_. I've asked the questions in places we _might_ get more data:
UX StackExchange: https://ux.stackexchange.com/questions/145232/do-any-major-e-commerce-companies-have-modals-in-their-checkout-process HackerNews: https://news.ycombinator.com/item?id=34133231 


**`Modals`** are _horrible_ and unnecessary in **`99%`** of the cases they are used by naive devs who do not _own_ the company they work for and have no "stake" in the outcome i.e. aren't compensated based on conversion rate.

In e-commerce checkout **`Modals`** are _massive_ anti-pattern and _none_ of the major e-commerce companies use them conversion and successful cart completion _matters_ to the bottom line.

We might not have the data from the **`Fork`** Analytics, but quite frankly it _really_ doesn't matter.
It's like having a debate about the policies of a minor political party 
when they will _never_ reach mainstream appeal.
It's just a pub conversation that goes nowhere.  💬 🙄 

# `Modals` == `Cigarettes`

Plenty of people _choose_ to **smoke `cigarettes`** [or vape, Heets/IQOS, etc... all the same nicotine fix!] 🚬  
Initially because they are _desperate_ for peer approval and subsequently because they are addicted ... 💀 

But **`smoking`** just doesn't make _any_ sense from a health, financial or cognitive perspective.
Again, this isn't a matter of ***opinion***, it's **science**.


`Modals` are the smoking of UI/UX, people only use them because they see other "kuel" people using them ...
They are a band-aid to a problem that people don't have the _engineering skill_ to fix; page response time.

![image](https://user-images.githubusercontent.com/194400/209488101-f9c02c43-dae7-4972-82ed-9c6d314a787a.png)

If you find yourself reaching for a **`cigarette`** / **`Modal`** ... 
Ask yourself: Am I _fixing_ the problem or making it ***worse***?


As for the _personal_ experience of buying _Country_ Vinyl records ... 😜 
Dunno if you're just trolling :trollface: 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/194400/209490422-f517076b-d8f1-4e91-81fa-e63f457246bc.png)

If you're "going back to add forgotten `items`" ...
`then` either you are having trouble deciding how to burn your cash or the site you're using has bad UX. 
The **`Amazon`** "bundle" is _definitely_ too big. But it doesn't do a full refresh on each page load.
**`Amazon`** knows that people load the bundle infrequently and never during checkout.
A `Modal` might be OK for a younger person with reasonable technical competence, 
but it's _horrible_ for "normal" people.

# No Thank You. 

We aren't going to use `Modals` in our App/UI. This isn't up for "debate". 🙅 
As much as I want to be diplomatic. This isn't a "discussion" I'm going to waste _any_ more time on. ⏳ == 💸 🔥 

If other trendy websites feel the need to use them, that's their [ill-informed] choice. 👌

**Comment by nelsonic** [comment]
https://youtu.be/uXs-zPc63kM?t=3007
<img width="887" alt="image" src="https://user-images.githubusercontent.com/194400/209491433-88f1efbf-f4cf-488d-993b-bf8670b5622e.png">

# Ouch ... 📉 

<img width="886" alt="image" src="https://user-images.githubusercontent.com/194400/209491966-0016463e-b569-449b-bd7e-c714a339ed78.png">

Just don't do it! It's not worth it. `Modals` are _baaaaaaaaaaaadddd_. 😢

**Comment by nelsonic** [comment]
Captured in: https://dwyl.github.io/book/auth/08-modals-antipattern.html

**Comment by nelsonic** [comment]
So glad someone `else` has created this:

You don't need a modal window: https://youdontneedamodalwindow.dev/

via: https://news.ycombinator.com/item?id=36056376

<img width="771" alt="Screenshot 2023-05-24 at 13 16 06" src="https://github.com/dwyl/product-ux-research/assets/194400/93d38f61-72b0-42f4-9da0-f1735d9f98bb">

sadly, most of the comments on HN are from hipsters who have never _seen_ an accessibility study
and think Modals are OK. But there are a handful of people in the comments who _get_ it.

**Comment by nelsonic** [comment]
https://dwyl.github.io/book/auth/08-modals-antipattern.html

**Comment by nelsonic** [comment]
While trying to view one of my playlists in Spotify I just got this full page interruption:

![image](https://github.com/dwyl/product-ux-research/assets/194400/0a532eb4-e6ec-4028-9e93-78c8f749b31b)

It's not enough for me to _pay_ them to RENT music, they also want permission to track me for marketing?! Fail.

**Comment by ndrean** [comment]
I think the "details" tag can be useful:

 <details>
<summary>click to view more</summary>  
Here are the details you want to read 
</details>

I helps to keep the flow a bit more tidy.

**Comment by nelsonic** [comment]
Yeah, nothing against the `details` tag if the `<summary>` is appropriate. 👌 
It's not the same as a `Modal` that pops over the content ...

**Comment by nelsonic** [comment]
While attempting to perform an action in `Amazon.es` shopping cart,
was just presented with this absurd `Modal`:

<img width="727" alt="Image" src="https://github.com/user-attachments/assets/566da8c7-ef31-4372-afb7-1afde8fbbca7" />

Translated:

<img width="727" alt="Image" src="https://github.com/user-attachments/assets/ccf827c5-9526-48dc-923f-a90cca998a60" />

Why is this interaction a `Modal`? 🤦‍♂ 
Why does clicking a button in the cart trigger a `Modal`?! 🤷‍♂ 
The `Modals` have infiltrated what used to be the highest performing checkout experience. 😢
