### ISSUE TITLE
Research: Release Notes! What are the *Best* examples we can find?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-ux-research#45]
What are the _best_ examples of release notes you can find for any `App`?
The best release notes are the ones that:
1. Clearly communicate what updates were made in the latest release including: 
  A. Feature improvements - shiny new things people really wanted
  B. Bug-fixes - things that were broken 
  C. performance enhancements 
  D. celebrate the ***`people`*** who made the release possible
2. Link to the issue(s) & PRs where the work was captured & performed
3. Screen Recordings of the features that `people` can play-back to learn how the feature works!

# Todo

Please find and share examples and be as specific as possible with:
+ [ ] screenshots, screen recordings, videos where available
+ [ ] copy-paste text and 
+ [ ] directly link to the example where possible.

**Comment by LuchoTurtle** [comment]
Haven't yet researched "good release notes" but the common practice seems to follow a template that is systematically updated on every release.
Big projects like [`Three.js`](https://github.com/mrdoob/three.js/releases/tag/r148) seem to be using this format, which credit each contributor along the way.

I feel for `dwyl`'s case, having a [`release-drafter`](https://github.com/release-drafter/release-drafter), combined with a tool like [`Chronicler`](https://chronicler.starchartlabs.org/) will make release notes much easier and automatic (for the most part, it will always need a human touch).

We should adopt [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), as it paves the way to [generating changelogs quite easily](https://github.com/orhun/git-cliff).

We can follow [GitLab's guide](https://docs.gitlab.com/ee/development/changelog.html) when writing a release template (or [`KeepAChangelog`](https://keepachangelog.com/en/1.0.0/)'s).

**Comment by nelsonic** [comment]
@LuchoTurtle the `Three.js` release notes: https://github.com/mrdoob/three.js/releases/tag/r148 
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/194400/210558844-125ce5db-8f32-4215-a9a4-216999b4c588.png">

A bullet point list with links. Those links are mostly to PRs. The PRs are themselves just referencing issues e.g:
https://github.com/mrdoob/three.js/pull/25165
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/194400/210559277-532bcfd5-2b23-425b-923d-74082c6fe9f2.png">

https://github.com/mrdoob/three.js/issues/24711
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/194400/210559542-c0883841-2d76-4560-ad99-fa16e914e73b.png">

Yes, **`Three.js`** is a _good_ Open Source project with _many_ `people` using it. 👍 
But these release notes are very much only interpretable by fellow developers, they aren't written for regular `people`.
Perhaps it's because non-technical people don't tend to ***`use`*** `Three.js`...

But this is **_definitely_ not** what I have in mind. 
I want the release notes to tell a _visual_ story. 
That means either a _Video_ that people can watch to see what new features were added.
or a `GIF` that shows just the section that was added. 
These can _initially_ be hand-made by the `person` who is leading the release/update.
But longer term, we should figure out how to automate this or at least delegate it to a [**`VA`**](https://www.fiverr.com/hire/virtual-assistance). 

A list of links is the "ordinary". We see this _everywhere_. 🥱  [**`#boring`**](https://youtu.be/jqzUPDk_MmQ)
https://github.com/FreeCAD/FreeCAD/releases/tag/0.20.2
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/194400/210560275-61a4c705-ac8f-4472-82ee-7dbfe27c1b1b.png">

# “_The difference between ordinary and extraordinary is that little `extra`_.” ~ Jimmy Johnson


I'm not saying I have the _answer_ yet! That's why I opened the issue to research.
We can certainly _start_ with a set of links on a page. 
But we need to know what our end-goal is.
And that is to have something "Wow!" 😍 
Something that **_busy_ non-technical `people`** take **`5 mins`** out of their day to read/watch.

**Comment by nelsonic** [comment]
The Miro updates are a good example:  https://miro.com/changelog/
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/194400/210562795-2a1aafdf-932a-4f94-a96f-0e226be2c1b4.png">

They often include `GIFs` of the functionality described in the release. 
Again, not saying this is the "Right" way to do it, but it's _far_ more non-technical person _friendly_ than a list of links.

**Comment by nelsonic** [comment]
Please see: https://www.launchnotes.com/blog/release-notes-examples#miro
